# Generated by Django 4.0.3 on 2023-04-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField()),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('moving', 'Moving'), ('maintenance', 'Maintenance')], max_length=12)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), (None, 'None')], max_length=5, null=True)),
                ('up_target_floor', models.IntegerField()),
                ('down_target_floor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
            ],
        ),
    ]
