# Generated by Django 4.0.3 on 2023-04-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='down_target_floor',
            new_name='ground_target_floor',
        ),
        migrations.RenameField(
            model_name='elevator',
            old_name='up_target_floor',
            new_name='top_target_floor',
        ),
    ]
